chore: Refactor SlevomatCodingStandard.Commenting.DocCommentSpacing.* rules
conversionxl/phpcs-ruleset pull request #10
Opened 2022-06-06 08:40 UTC by saas786

After setting `linesCountBetweenAnnotationsGroups` to `0`, creating unique annotation groups, causes phpcbf to run infinitely. Hence failing it.

So combined groups into single group.

Removed duplicate `SlevomatCodingStandard.Commenting.DocCommentSpacing` rule.

2022-07-11 12:04 UTC, pawelkmpt commented
Can you provide example files you tested it on?

2022-07-18 10:36 UTC, saas786 commented
> Can you provide example files you tested it on?

Can you most of the files, here is one example:

`composer exec -v phpcbf -- "src/Plugin/DataProviders/UserLearningDataProvider.php"`

---

Without this PR:
![IQ50v2rVBg](https://user-images.githubusercontent.com/1642796/179494324-57b92685-2379-4231-ac4d-21f2c086e469.png)

---

After / With this PR:
![a35rxEJHPF](https://user-images.githubusercontent.com/1642796/179494352-8068c257-5989-426d-8179-07271c79a6cb.png)

2022-07-28 06:47 UTC, saas786 commented
@pawelkmpt @lkraav 

Can we merge this, so I can rebase https://github.com/conversionxl/phpcs-ruleset/pull/11
and we can merge it too, today if possible.

I have tested both so we can merge these safely. We can `exclude` few more rules in subsequent PRs.

2022-07-29 10:48 UTC, pawelkmpt requested changes
I tested and it fails for me as well so it's not OS issue. 

Please add to the commit message:

```
Setting `linesCountBetweenAnnotationsGroups` to `0` with unique annotation groups, causes `phpcbf` to run infinitely. Hence failing it.

This fixes the problem with combining elements into single group.
```

2022-07-29 11:01 UTC, pawelkmpt approved these changes

2022-07-29 11:01 UTC, merged