Tweak rules
conversionxl/phpcs-ruleset pull request #13
Opened 2022-09-02 15:18 UTC by saas786

2022-09-07 08:51 UTC, pawelkmpt reviewed
Branch name should be `syed/chore/slevomat`

2022-09-07 08:51 UTC, pawelkmpt commented on CXL/ruleset.xml
> +        <!-- Class method we allow, One Line Doc Comment where there's only 1 annotation present -->
This comment is unclear for me. Did you mean:

```suggestion
        <!-- We allow multiline doc comment for class when there's only 1 annotation present -->
```

?

2022-09-07 12:05 UTC, pawelkmpt commented on CXL/ruleset.xml
> +        <!-- Class method we allow, One Line Doc Comment where there's only 1 annotation present -->
Actually it should've been:

```diff
- We allow multiline doc comment for class when there's only 1 annotation present
+ We allow multiline doc comment for class or method when there's only 1 annotation present
```

2022-09-08 08:19 UTC, pawelkmpt requested changes
What did you change in recent push? I don't see ruleset comment updated.

Please also update commit message in 782d7a38e0bdb72b6a795e94a53f07c1967c6128
and add "closes #4"

2022-09-09 14:02 UTC, saas786 commented
@pawelkmpt 

> Please also update commit message in https://github.com/conversionxl/phpcs-ruleset/commit/782d7a38e0bdb72b6a795e94a53f07c1967c6128

Update commit message to 

from
**(chore: Add `@inheritDoc` to `annotationsGroups` rule)**
to
**`?`**

2022-09-09 14:05 UTC, pawelkmpt commented
> @pawelkmpt
> 
> > Please also update commit message in [782d7a3](https://github.com/conversionxl/phpcs-ruleset/commit/782d7a38e0bdb72b6a795e94a53f07c1967c6128)
> 
> Update commit message to
> 
> from **(chore: Add `@inheritDoc` to `annotationsGroups` rule)** to **`?`**

I think I pointed the wrong commit. I meant the one with `RequireOneLineDocComment` to match commit message with comment in xml. I see you updated it now 👍

2022-09-09 14:06 UTC, pawelkmpt approved these changes

2022-09-09 14:15 UTC, merged